# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'DB_User_Category',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='UserDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_db_name', models.CharField(db_index=True, max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myDB', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DB_UserDB',
            },
        ),
        migrations.CreateModel(
            name='UserMolecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mol', models.IntegerField(db_index=True)),
                ('added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myMols', to='user_section.UserDataBase')),
            ],
            options={
                'ordering': ('user_db',),
                'db_table': 'DB_UserMol',
            },
        ),
        migrations.AddField(
            model_name='usercategory',
            name='user_db',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myCategory', to='user_section.UserDataBase'),
        ),
    ]
