# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'DB_Category',
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='fpCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'DB_fpCategory',
                'verbose_name': 'fpcategory',
                'verbose_name_plural': 'fpcategories',
            },
        ),
        migrations.CreateModel(
            name='MoleculeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSU_CID', models.IntegerField()),
                ('Py_MW', models.FloatField()),
                ('AtomNumber', models.IntegerField()),
                ('BondNumber', models.IntegerField()),
                ('RingNumber', models.IntegerField()),
                ('LogP', models.FloatField()),
                ('PUB_CID', models.IntegerField()),
                ('Formula', models.TextField()),
                ('InChI', models.TextField()),
                ('SMILES', models.TextField()),
                ('SMARTS', models.TextField()),
                ('FormalCharge', models.IntegerField()),
                ('HBA', models.IntegerField()),
                ('HBD', models.IntegerField()),
                ('RotateBond', models.IntegerField()),
                ('RDKit_MW', models.FloatField(null=True)),
                ('yaChI', models.TextField(null=True)),
                ('TPSA', models.FloatField()),
                ('InChIKey', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='molecules', to='index.Category')),
            ],
            options={
                'ordering': ('SSU_CID',),
                'db_table': 'DB_Data',
            },
        ),
        migrations.CreateModel(
            name='MopacData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSU_CID', models.IntegerField()),
                ('Heat', models.FloatField(null=True)),
                ('Total_Energy', models.FloatField(null=True)),
                ('Elec_Energy', models.FloatField(null=True)),
                ('Point_Group', models.FloatField(null=True)),
                ('COSMO_Area', models.FloatField(null=True)),
                ('COSMO_Volume', models.FloatField(null=True)),
                ('Ion_Potential', models.FloatField(null=True)),
                ('HOMO', models.FloatField(null=True)),
                ('LUMO', models.FloatField(null=True)),
                ('Dimensions', models.TextField(null=True)),
                ('Charge', models.TextField(null=True)),
            ],
            options={
                'ordering': ('SSU_CID',),
                'db_table': 'DB_Mopac_1',
            },
        ),
    ]
