# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moleculedata',
            name='AtomNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='BondNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='FormalCharge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='Formula',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='HBA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='HBD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='InChI',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='InChIKey',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='LogP',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='PUB_CID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='Py_MW',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='RingNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='RotateBond',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='SMARTS',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='SMILES',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='moleculedata',
            name='TPSA',
            field=models.FloatField(null=True),
        ),
    ]
