# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20171013_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mopacdata',
            name='Point_Group',
            field=models.TextField(null=True),
        ),
    ]
